import type { CompiledRecipe } from './compile';

/** Emit a Storybook CSF file with a variant × state matrix. */
export function emitStories(compiled: CompiledRecipe): string {
  const { recipe, variantAttrs } = compiled;
  const axes = Object.entries(recipe.variants ?? {});
  const defaultVariants = recipe.defaultVariants ?? {};

  const argTypes = axes.map(([axis, values]) => {
    const opts = Object.keys(values)
      .map(v => `'${v}'`)
      .join(', ');
    return `    ${axis}: { control: 'select', options: [${opts}] },`;
  });

  const args = axes.map(([axis]) => {
    const d = defaultVariants[axis] ?? Object.keys(recipe.variants![axis])[0];
    return `    ${axis}: '${d}',`;
  });

  // Build a simple matrix story for the first two axes (appearance × size typically)
  const [axisA, valuesA] = axes[0] ?? ['appearance', { secondary: {} }];
  const [axisB, valuesB] = axes[1] ?? [null, null];

  let matrixBody: string;
  if (axisB && valuesB) {
    matrixBody = `
export const Matrix: Story = {
  render: () => (
    <div style={{ display: 'grid', gap: 12 }}>
      {([${Object.keys(valuesA)
        .map(v => `'${v}'`)
        .join(', ')}] as const).map(${axisA} => (
        <div key={${axisA}} style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <strong style={{ width: 100 }}>${axisA}={${axisA}}</strong>
          {([${Object.keys(valuesB)
            .map(v => `'${v}'`)
            .join(', ')}] as const).map(${axisB} => (
            <${recipe.component} key={${axisB}} ${axisA}={${axisA}} ${axisB}={${axisB}}>
              {${axisB}}
            </${recipe.component}>
          ))}
          <${recipe.component} ${axisA}={${axisA}} disabled>
            disabled
          </${recipe.component}>
        </div>
      ))}
    </div>
  ),
};
`;
  } else {
    matrixBody = `
export const Matrix: Story = {
  render: () => (
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
      {([${Object.keys(valuesA)
        .map(v => `'${v}'`)
        .join(', ')}] as const).map(v => (
        <${recipe.component} key={v} ${axisA}={v}>{v}</${recipe.component}>
      ))}
    </div>
  ),
};
`;
  }

  return `/**
 * Generated by @fluentui/ds-compiler — do not edit by hand.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { ${recipe.component} } from './index';

const meta: Meta<typeof ${recipe.component}> = {
  title: 'Fluent2 CSS/${recipe.component}',
  component: ${recipe.component},
  args: {
${args.join('\n')}
    children: '${recipe.component}',
  },
  argTypes: {
${argTypes.join('\n')}
  },
};

export default meta;
type Story = StoryObj<typeof ${recipe.component}>;

export const Default: Story = {};

export const Disabled: Story = {
  args: { disabled: true },
};

export const DisabledFocusable: Story = {
  args: { disabled: true, disabledFocusable: true },
};
${matrixBody}
`;
}
