import type { CompiledRecipe } from './compile';
import { camelToKebab } from './compile';
import type { SlotStyles, Style, StyleValue } from './schema';

function resolveValue(value: StyleValue): string {
  if (typeof value === 'number') return String(value);
  // Replace every $tokenName reference inside the value (supports shorthands).
  return value.replace(/\$([A-Za-z][A-Za-z0-9]*)/g, 'var(--$1)');
}

function decls(style: Style, indent: string): string {
  return Object.entries(style)
    .map(([prop, value]) => `${indent}${camelToKebab(prop)}: ${resolveValue(value)};`)
    .join('\n');
}

function emitSlots(compiled: CompiledRecipe, slotStyles: SlotStyles, rootSelector: string, indent = ''): string {
  const blocks: string[] = [];
  for (const [slot, style] of Object.entries(slotStyles)) {
    const selector = slot === 'root' ? rootSelector : `${rootSelector} .${compiled.classNames[slot]}`;
    blocks.push(`${indent}${selector} {\n${decls(style, indent + '  ')}\n${indent}}`);
  }
  return blocks.join('\n\n');
}

const PSEUDO: Record<string, string> = {
  hover: 'hover',
  active: 'active',
  focusVisible: 'focus-visible',
  focus: 'focus',
};

export function emitCss(compiled: CompiledRecipe): string {
  const { recipe, manifest, variantAttrs, rootClass } = compiled;
  const root = `.${rootClass}`;
  const out: string[] = [];

  out.push('/* Generated by @fluentui/ds-compiler — do not edit by hand */');
  out.push('@layer ds.base, ds.variants, ds.states, ds.compound, ds.interactions, ds.conditions, ds.raw;');
  out.push('');

  // base
  out.push('@layer ds.base {');
  if (recipe.localTokens && Object.keys(recipe.localTokens).length) {
    out.push(`  ${root} {`);
    for (const [name, value] of Object.entries(recipe.localTokens)) {
      out.push(`    ${name}: ${resolveValue(value)};`);
    }
    out.push('  }');
    out.push('');
  }
  out.push(emitSlots(compiled, recipe.base, root, '  '));
  out.push('}');
  out.push('');

  // variants
  if (recipe.variants) {
    out.push('@layer ds.variants {');
    const blocks: string[] = [];
    for (const [axis, values] of Object.entries(recipe.variants)) {
      for (const [valueName, slotStyles] of Object.entries(values)) {
        blocks.push(emitSlots(compiled, slotStyles, `${root}[${variantAttrs[axis]}="${valueName}"]`));
      }
    }
    out.push(
      blocks
        .join('\n\n')
        .split('\n')
        .map(l => (l ? `  ${l}` : l))
        .join('\n'),
    );
    out.push('}');
    out.push('');
  }

  // states
  if (recipe.states) {
    out.push('@layer ds.states {');
    const blocks: string[] = [];
    for (const [stateName, stateStyles] of Object.entries(recipe.states)) {
      const desc = manifest.states[stateName];
      if (!desc) continue;
      if (desc.kind === 'presence') {
        blocks.push(emitSlots(compiled, stateStyles as SlotStyles, `${root}[${desc.attr}]`));
      } else {
        for (const [enumValue, slotStyles] of Object.entries(stateStyles as Record<string, SlotStyles>)) {
          blocks.push(emitSlots(compiled, slotStyles, `${root}[${desc.attr}="${enumValue}"]`));
        }
      }
    }
    out.push(
      blocks
        .join('\n\n')
        .split('\n')
        .map(l => (l ? `  ${l}` : l))
        .join('\n'),
    );
    out.push('}');
    out.push('');
  }

  // compound
  if (recipe.compoundVariants?.length) {
    out.push('@layer ds.compound {');
    const blocks: string[] = [];
    for (const cv of recipe.compoundVariants) {
      let selector = root;
      if (cv.variants) {
        for (const [axis, value] of Object.entries(cv.variants)) {
          selector += `[${variantAttrs[axis]}="${value}"]`;
        }
      }
      if (cv.states) {
        for (const [stateName, value] of Object.entries(cv.states)) {
          const desc = manifest.states[stateName];
          if (!desc) continue;
          selector += desc.kind === 'presence' ? `[${desc.attr}]` : `[${desc.attr}="${value}"]`;
        }
      }
      blocks.push(emitSlots(compiled, cv.css, selector));
    }
    out.push(
      blocks
        .join('\n\n')
        .split('\n')
        .map(l => (l ? `  ${l}` : l))
        .join('\n'),
    );
    out.push('}');
    out.push('');
  }

  // interactions
  if (recipe.interactions) {
    out.push('@layer ds.interactions {');
    const blocks: string[] = [];
    for (const [slot, map] of Object.entries(recipe.interactions)) {
      for (const [pseudo, style] of Object.entries(map)) {
        if (!style) continue;
        const base = slot === 'root' ? root : `${root} .${compiled.classNames[slot]}`;
        const guard =
          pseudo === 'hover' || pseudo === 'active' ? ':not([data-disabled]):not([data-disabled-focusable])' : '';
        const selector = `${base}${guard}:${PSEUDO[pseudo] ?? pseudo}`;
        blocks.push(`${selector} {\n${decls(style, '  ')}\n}`);
      }
    }
    out.push(
      blocks
        .join('\n\n')
        .split('\n')
        .map(l => (l ? `  ${l}` : l))
        .join('\n'),
    );
    out.push('}');
    out.push('');
  }

  // conditions
  if (recipe.conditions) {
    out.push('@layer ds.conditions {');
    if (recipe.conditions.forcedColors) {
      out.push('  @media (forced-colors: active) {');
      out.push(emitSlots(compiled, recipe.conditions.forcedColors, root, '    '));
      out.push('  }');
    }
    if (recipe.conditions.reducedMotion) {
      out.push('  @media (prefers-reduced-motion: reduce) {');
      out.push(emitSlots(compiled, recipe.conditions.reducedMotion, root, '    '));
      out.push('  }');
    }
    if (recipe.conditions.rtl) {
      for (const [slot, style] of Object.entries(recipe.conditions.rtl)) {
        const sel =
          slot === 'root'
            ? `[dir="rtl"] ${root}, ${root}[dir="rtl"]`
            : `[dir="rtl"] ${root} .${compiled.classNames[slot]}`;
        out.push(`  ${sel} {\n${decls(style, '    ')}\n  }`);
      }
    }
    out.push('}');
    out.push('');
  }

  // raw
  if (recipe.raw?.length) {
    out.push('@layer ds.raw {');
    for (const block of recipe.raw) {
      out.push(`  /* raw: ${block.reason} */`);
      out.push(
        block.css
          .split('\n')
          .map(l => (l ? `  ${l}` : l))
          .join('\n'),
      );
    }
    out.push('}');
    out.push('');
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

export function emitThemeCss(preset: CompiledRecipe['preset']): string {
  const out: string[] = [];
  out.push('/* Generated by @fluentui/ds-compiler — design tokens as CSS variables */');
  out.push(':root {');
  for (const [name, value] of Object.entries(preset.tokens)) {
    out.push(`  --${name}: ${value};`);
  }
  out.push('}');
  out.push('');
  if (preset.darkTokens && Object.keys(preset.darkTokens).length) {
    out.push(':root[data-theme="dark"], [data-theme="dark"] {');
    for (const [name, value] of Object.entries(preset.darkTokens)) {
      out.push(`  --${name}: ${value};`);
    }
    out.push('}');
    out.push('');
  }
  return out.join('\n');
}
