import type { CompiledRecipe } from './compile';

/**
 * Emit a thin React wrapper that:
 * 1. Accepts headless props + DS variant props
 * 2. Calls headless useX / renderX
 * 3. Writes DS variant data-* attrs + stable class names onto slots
 */
export function emitTsx(compiled: CompiledRecipe): string {
  const { recipe, manifest, classNames, variantAttrs } = compiled;
  const variantAxes = Object.keys(recipe.variants ?? {});
  const defaults = recipe.defaultVariants ?? {};

  const variantTypeLines = variantAxes.map(axis => {
    const values = Object.keys(recipe.variants![axis])
      .map(v => `'${v}'`)
      .join(' | ');
    return `  ${axis}?: ${values};`;
  });

  const defaultLines = variantAxes.map(axis => {
    const d = defaults[axis];
    return d ? `    ${axis} = '${d}',` : `    ${axis},`;
  });

  const attrAssignLines = variantAxes.map(axis => {
    const attr = variantAttrs[axis];
    return `  if (${axis} !== undefined) {\n    (state.root as Record<string, unknown>)['${attr}'] = ${axis};\n  }`;
  });

  const classAssignLines = Object.entries(classNames).map(([slot, className]) => {
    if (slot === 'root') {
      return `  state.root.className = [state.root.className, '${className}'].filter(Boolean).join(' ');`;
    }
    return `  if (state.${slot}) {\n    state.${slot}.className = [state.${slot}.className, '${className}'].filter(Boolean).join(' ');\n  }`;
  });

  return `/**
 * Generated by @fluentui/ds-compiler — do not edit by hand.
 * Recipe: ${recipe.component} (${recipe.source ?? 'unspecified source'})
 */
'use client';

import * as React from 'react';
import {
  ${manifest.hooks.use} as useHeadless,
  ${manifest.hooks.render} as renderHeadless,
} from '${manifest.packageName}/${manifest.subpath}';
import type {
  ${manifest.types.props} as HeadlessProps,
  ${manifest.types.state} as HeadlessState,
} from '${manifest.packageName}/${manifest.subpath}';

export type ${recipe.component}Variants = {
${variantTypeLines.join('\n')}
};

export type ${recipe.component}Props = HeadlessProps & ${recipe.component}Variants;

export type ${recipe.component}State = HeadlessState & Required<Pick<${recipe.component}Variants, ${
    variantAxes.map(a => `'${a}'`).join(' | ') || 'never'
  }>>;

function use${recipe.component}Styles(state: ${recipe.component}State, variants: ${recipe.component}Variants): void {
${variantAxes.map(a => `  const ${a} = variants.${a} ?? state.${a};`).join('\n') || '  // no variants'}

${attrAssignLines.join('\n') || '  // no variant attrs'}

${classAssignLines.join('\n')}
}

/**
 * Fluent 2 styled ${recipe.component} built on the headless primitive.
 */
export const ${recipe.component} = React.forwardRef(function ${recipe.component}(
  props: ${recipe.component}Props,
  ref: React.ForwardedRef<HTMLButtonElement | HTMLAnchorElement>,
) {
  const {
${defaultLines.join('\n') || '    // no variants'}
    ...rest
  } = props;

  const state = useHeadless(rest, ref) as ${recipe.component}State;
${variantAxes.map(a => `  state.${a} = ${a}${defaults[a] ? ` ?? '${defaults[a]}'` : ''}!;`).join('\n') || ''}

  use${recipe.component}Styles(state, { ${variantAxes.join(', ')} });

  return renderHeadless(state);
});

${recipe.component}.displayName = '${recipe.component}';
`;
}

export function emitIndex(compiled: CompiledRecipe): string {
  const name = compiled.recipe.component;
  return `export { ${name} } from './${name}';
export type { ${name}Props, ${name}State, ${name}Variants } from './${name}';
`;
}
